#!/usr/bin/env bash

## Variables that control the behavior of the molecular modeling tools.
##
export GEMS_LOGGING_LEVEL='error'
## Logging level options: error, info, debug
##
export GEMS_FORCE_SERIAL_EXECUTION='True'  
## Setting this to False will not work unless you make some significant
## changes to how the code here works. 
## This is because setting this to false will allow GEMS to spawn certain
## proceures as detached child processes. Once that is done, GEMS will then
## exit the main process. At that point the container, and any incomplete
## child processes, will be killed.
## If you want to set this to false, then you need to ensure that the first
## process in the container never ends, e.g., 'tail -f /dev/null'.
##
export GEMS_MD_TEST_WORKFLOW='False'  
## Setting this to true runs all MD actions for only a couple steps.
## This is useful if you just want to ensure that the correct MD code is
## being run and you plan to do the real MD work once that is confirmed.
## Setting this to true will result in bad (because too short) MD actions.


## Variables that control the behavior of Docker.
##
YYYYMMDDHHMM="$(date +%Y-%m-%d-%H-%M)"
##
export USER_UID="$( id -u )"
export USER_GID="$( id -g )"
export USER_NAME="$( id -un )"
export PREFIX=${USER_NAME}
##
SERVICE="delegator"
CONTAINER_PREFIX="${PREFIX}-${SERVICE}"
DOCKER_COMPOSE_BUILD_FILE="./docker-compose.build.yml"
DOCKER_COMPOSE_RUN_FILE="./docker-compose.run.yml"
##
export FROM_IMAGE="python:3.9.17-bullseye"
export IMAGE_NAME="glycam-web-${SERVICE}"
export IMAGE_TAG="1.0_blf_2025-11-26-00" 
export DOCKERFILE_DIR="./images/delegator"
export DOCKERFILE="Dockerfile"
export CONTAINER_NAME="${CONTAINER_PREFIX}"
export DELEGATOR_ENV_FILE="./env/delegator.env"

export FILE_MESSAGE="""
# This file has been generated by a script. Do not edit the values here.
# If you need to change the values, then change them in their settings file.
# $( date )
"""


## Create a file with this name to override settings here.
if [ -f LocalSettings.bash ]; then
	source LocalSettings.bash
fi
