#!/usr/bin/env bash

## Variables that control the behavior of the molecular modeling tools.
##
## See also the git-settings.bash file regarding the code versions that are used.
##
export GEMS_LOGGING_LEVEL='error'
## Logging level options: error, info, debug
##
export GEMS_FORCE_SERIAL_EXECUTION='True'  
## Setting this to False will not work unless you make some significant
## changes to how the code here works. 
## This is because setting this to false will allow GEMS to spawn certain
## proceures as detached child processes. Once that is done, GEMS will then
## exit the main process. At that point the container, and any incomplete
## child processes, will be killed.
## If you want to set this to false, then you need to ensure that the first
## process in the container never ends, e.g., 'tail -f /dev/null'.
##
export GEMS_MD_TEST_WORKFLOW='False'  
## Setting this to true runs all MD actions for only a couple steps.
## This is useful if you just want to ensure that the correct MD code is
## being run and you plan to do the real MD work once that is confirmed.
## Setting this to true will result in bad (because too short) MD actions.
##
export KEEP_TEMPORARY_FILES='True'
## Setting this to true means that all intermediate files are retained.
## These files contain information regarding problems found in the input.
## For example, if duplicate entries is not allowed, then the files containing
## the list of duplicate entries will be retained.
## If this is set to 'False', figuring out what went wrong can be a challenge.


## Variables that control the behavior of Docker.
##
export YYYYMMDDHHMM="$(date +%Y-%m-%d-%H-%M)"
export AUTOGENERATED_FILE_PREFIX='_autogen'
##
export USER_UID="$( id -u )"
export USER_GID="$( id -g )"
export USER_NAME="$( id -un )"
export PREFIX=${USER_NAME}
export DEPENDENCIES_PATH="./deps/"
export INPUTS_PATH="./input-output/inputs/"
export TESTS_PATH="./input-output/tests/"
##
export WORK_PATH="./input-output/work/"
export OUTPUTS_PATH="./input-output/outputs/"
## Entries in WORK_PATH and OUTPUTS_PATH are further organized by entity/service, e.g. sequence/cb.
##   Entries are further subdivided for organizational purposes. For example, in WORK_PATH/sequence/cb, 
##   output is further subdivided into 'Builds' and 'Sequences'.
## Users cannot alter the behavior of WORK_PATH, but can alter OUTPUTS_PATH.
## By default, information in OUTPUTS_PATH is subdivided by CONFIG_DATE found in AUTOGENERATED_FILE_PREFIX_config.sh. 
##   That information, among others, can be overridden in SessionSettings.bash. Further documentation is elsewhere.


SERVICE="delegator"
CONTAINER_PREFIX="${PREFIX}-${SERVICE}"
DOCKER_COMPOSE_BUILD_FILE="./docker-compose.build-image.yml"
DOCKER_COMPOSE_COMPILE_FILE="./docker-compose.compiler.yml"
DOCKER_COMPOSE_RUN_FILE="./docker-compose.run.yml"
##
export FROM_IMAGE="python:3.9.17-bullseye"
export IMAGE_NAME="${PREFIX}-glycam-web-${SERVICE}"
export IMAGE_TAG="1.0_blf_2026-01-12-03" 
export DOCKERFILE_DIR="./images/delegator"
export DOCKERFILE="Dockerfile"
export HOST_NAME="${CONTAINER_PREFIX}"
export CONTAINER_NAME="${CONTAINER_PREFIX}"
export DELEGATOR_ENV_FILE="./env/delegator.env"
export IMG_USER_NAME='glycam'
export IMG_GROUP_NAME='glycam'

export FILE_MESSAGE="""
# This file has been generated by a script. Do not edit the values here.
# If you need to change the values, then change them in their settings file.
# $( date )
"""


## Create a file with this name to override settings here.
if [ -f LocalSettings.bash ]; then
	source LocalSettings.bash
fi
