services:
  #########################################################
  #        GLYCAM-Web Delegator Service                   #
  #########################################################
  delegator:
    image: ${IMAGE_NAME}:${TAG_NAME}
    hostname: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    user: ${IMG_USER_NAME}:${IMG_GROUP_NAME}
    dns:  8.8.8.8
    env_file:
      - ${DELEGATOR_ENV_FILE}
    volumes:
      - ./deps/gems:/programs/gems/
      - ${INPUTS_PATH}:/inputs/
      - ${WORK_PATH}:/work/
      - ${TESTS_PATH}:/tests/
      - ${OUTPUTS_PATH}:/outputs/
    command: bash -c "${GEMS_COMMAND}"


