#!/usr/bin/env bash
##############################################################################################################
#
# This script provides error messages generated by child processes at runtime. 
#
# The name of a script containing the error information must be given as an argument.
#
# The following locations must be passed to this script as arguments. See below for details.
# The locations must be visible inside the container.
#
#       Work_Dir_Log_File   :  Log file possibly containing error messages
#       Proj_Dir_Log_File   :  Log file where results should be written
#
# Error messages generated here are intended for use at runtime will include the following information:
#
#       Error_Numbers
#       Error_Briefs
#       Error_Meanings
#
# How those get used will depend on the code using them.
#
# Multiple Errors
#
#     If multiple errors are detected, the Error Number is '99'. The individual errors will be written
#     to the Error_log.txt file in the project directory.
#
#########################################
#
# How to use this script
#
# 1. Create a mapfile to contain the results:
#
#    the_db_file="/sysetc/input_error_db_file.bash" # replace with the actual file
#    the_wd="/path/to/the/work/directory"           # from inside the container
#    the_pd="/path/to/the/project/directory"        # from inside the container
#
#    # note .............. v v  both of these arrows are needed.
#    mapfile -t error_data < <(
#        /sysetc/build_error.bash \
#            "${the_db_file}" \
#            "${the_wd}" \
#            "${the_pd}"
#    )
#
#    # You can do it all on one line, if you prefer:
#    mapfile -t error_data < <(/sysetc/build_error.bash "${the_db_file}" "${the_wd}" "${the_pd}" )
# 
# 2. Check **IMMEDIATELY** after the mapfile line above for the return
#
#       ## ${PIPESTATUS[0]} is the return values for build_error.bash 
#       ## ${PIPESTATUS[1]} is for the mapfile creation
#       script_exit_code="${PIPESTATUS[0]}"
#       
# 3. Check if the script failed
#
#       if (( script_exit_code != 0 )); then
#           echo "External script failed with exit code: $script_exit_code"
#           echo "If any message was returned it will follow:"
#           echo "Message: >>>${error_data[0]}<<<"
#           exit "$script_exit_code"
#       fi
#
# 4. Accessing the results is easy.
#
#       echo "the error number is:  ${error_data[0]}"
#       echo "the error brief is:   ${error_data[1]}"
#       echo "the error meaning is: ${error_data[2]}"
#
##############################################################################################################

if [ -z "${1}" ] ; then
	echo "The path to the error database file must be provided."
	exit 1
fi
if [ -z "${2}" ] ; then
	echo "The path to the work directory must be provided."
	exit 1
fi
if [ -z "${3}" ] ; then
	echo "The path to the project directory must be provided."
	exit 1
fi

Work_Dir_Log_File="${2}"
Proj_Dir_Log_File="${3}"

source ${1}

Number_of_Errors="$( grep -c -E ${ALL_ERROR_GREP} )"

if [ "${Number_of_Errors}" -eq "0" ] ; then
	echo "0"
	echo "No Errors Found"
	echo "No error log will be written."
fi

#### finish logic...
if [ "${Number_of_Errors}" -gt "1" ] ; then
	echo "99"
	echo "Multiple Errors Found"
	echo "See ${Proj_Dir_Log_File} for details"
fi

echo "${the_error_number}"
echo "${the_error_brief}"
echo "${the_error_meaning}"
