#!/usr/bin/env bash

##############################################################################################################
##############################################################################################################
#
#  This file has multiple purposes. 
#
#  Relevant to all purposes:  Provide an error-message database.
#
#    Purpose 1: Simplify human-friendly error message generation at runtime.
#
#               The 'build_error.bash' file contains auxiliary functions that use this information.
#
#    Purpose 2: Provide infrastructure for automated error message documentation that is assured
#               to be up-to-date with the actual error messages.
#                 
#               The file build_docs.bash is the utility for generating the documentation.                 
#               See below for information about additional infrastructure in this file.
#
##############################################################################################################
##############################################################################################################


##############################################################################################################
## For all purposes: Provide an error-message database.
#                    See functions.bash for convenient usage utilities and for examples.
##############################################################################################################
##
# The following are the arrays that store the data. They are filled out below.
# The keys for all of these arrays are the error number.
declare -A Error_Briefs           # Abbreviated, descriptive message. Five words or less, ideally.
declare -A Error_Meanings         # Sentence length user-friendly meaning of the message.
declare -A Error_Generic_Text     # The text generated by the code, with variables in angle braces.
declare -A Source_File_and_Lines  # Path to the error in the source code file, with line number.
declare -A Error_Grep_Strings     # String to use if grepping for this error message.
#
# The is relevant to the database, but is primarily useful for the documentation generation.
# Minimum and maximum numbers assigned to errors here.
Min_Err_Number="571"
Max_Err_Number="597" # allows up to err number = 599
#
# Text to be used when directing the user to additional information.
More_Info_Text="Please see the GLYCAM_Delegator_Docker/docs directory for more information."
#
## Log file to query (if there are more, a rewrite is needed)
#Work_Dir_Log_File="${Work_Directory}/gpBuilder.log"
## Log file to write results to
#Proj_Dir_Log_File="${Project_Directory}/Error_log.txt"
##
##############################################################################################################

##############################################################################################################
## Automating the generation of error-message documentation.
##############################################################################################################
#
# Name of the documentation file to be written.
Document_Name="GlycoProtein_GMML2_Error_Details_autogen_.md"
#
# Name of this service to be used within the file named above
Service_Name="GlycoProtein Builder"
#
##############################################################################################################

Error_Briefs=(
   ["571"]="Incorrect Site Identifier Format"
   ["572"]="Missing Anomeric Carbon"
   ["573"]="Single-Residue Sugar Error"
   ["574"]="Unsupported Glycosylation Site"
   ["575"]="Missing Required Connection Atom"
   ["576"]="Missing Target Glycosite Residue"
   ["577"]="Multiple Connections to an Aglycone"
   ["578"]="Empty Sequence"
   ["579"]="Easter Egg Validation Failure"
   ["580"]="Space Character inside Sequence"
   ["581"]="Forbidden Character in Sequence"
   ["582"]="Mismatching Bracket Structure"
   ["583"]="Labeled Sequences Unsupported"
   ["584"]="Sequence Graph Disconnectivity"
   ["585"]="Missing Element Definition"
   ["586"]="Missing Atomic Mass Metadata"
   ["587"]="Missing Amino Acid Metadata"
   ["588"]="Conformation Inconsistency"
   ["589"]="Conformer Weight Mismatch"
   ["590"]="Disconnected Residues"
   ["591"]="Missing Dihedral Angles/Metadata"
   ["592"]="Unknown Rotamer Configuration Type"
   ["593"]="Carbohydrate Parent Residue Removal"
   ["594"]="PDB CONECT ID Parsing Failure"
   ["595"]="PDB CONECT Atom Missing"
   ["596"]="PDB File Open Failure"
   ["597"]="Prep File Read Failure"
)
Error_Meanings=(
   ["571"]="The format used for your glycosylation site could not be understood."
   ["572"]="The anomeric carbon (or other anomeric atom) could not be found in a monosaccharide residue."
   ["573"]="Monosaccharides with an aglycone are expected to have at least 2 residues."
   ["574"]="Glycosylation was requested for a residue other than ASN, THR, SER or TYR."
   ["575"]="A residue does not contain a key atom for making a connection."
   ["576"]="The residue to be glycosylated could not be found."
   ["577"]="An aglycone with multiple monosaccharides is not supported."
   ["578"]="The provided sequence is empty."
   ["579"]="We found a cake in your sequence! And the cake is a lie!"
   ["580"]="Sequences cannot contain spaces."
   ["581"]="Your sequence contains a character that is not expected."
   ["582"]="One of your brackets (of whatever type) was not part of a pair."
   ["583"]="Sequences containing custom labels are not yet supported."
   ["584"]="A part of your sequence could not be connected to the rest of it."
   ["585"]="The element designation is unknown to this code."
   ["586"]="The code does not know the atomic mass for this element."
   ["587"]="This amino acid is not known to the code."
   ["588"]="The given and expected numbers of linkage conformers differs."
   ["589"]="The given and expected weights of linkage conformers differs."
   ["590"]="Two residues that were expected to connect cannot be connected."
   ["591"]="The dihedral angles and/or probabilities for a linkage are not known."
   ["592"]="The code does not know the meaning of the type given for a rotamer."
   ["593"]="A parent residue was removed by chance, and likely by accident."
   ["594"]="A CONECT card in the PDB file could not be parsed."
   ["595"]="The atom's number was not found in the CONECT cards."
   ["596"]="The PDB file could not be opened/read."
   ["597"]="The Prep file could not be opened/read."
)
Error_Generic_Text=(
   ["571"]="userSelection (<userSelection>) for residue to glycosylate is incorrect format. Must be chain_residueNumber_insertionCode. InsertionCode is optional. Chain can be ? if no chain numbers are in input. Examples: ?_24_? or ?_24 will use the first residue it encounters numbered 24. A_24_B is A chain, residue 24, insertion code B"
   ["572"]="Did not find a C1 or C2 with a foreign neighbor in residue: <residueStringId>, thus no anomeric atom was found."
   ["573"]="Reducing residue and aglycone requested for Carbohydrate with name <glycanName>, but it doesn't have more than 1 residue"
   ["574"]="Problem creating glycosylation site. The amino acid requested: <residueId> has name (<name>) that isn't supported. Currently you can glycosylate ASN, THR, SER or TYR."
   ["575"]="Error: atom '<name>' not found in residue <residueId> with atoms: <list of atoms>"
   ["576"]="Error: Did not find a residue with id matching <proteinResidueId>"
   ["577"]="Error: found more than 1 linkage to aglycone in <glycanInput>"
   ["578"]="Error: sequence is empty:>>><sequence><<<"
   ["579"]="Error: the cake is a lie:>>><sequence><<<"
   ["580"]="Error: sequence contains a space:>>><sequence><<<"
   ["581"]="Error: sequence cannot contain this:'<char>':>>><sequence><<<"
   ["582"]="Did not find corresponding '<bracket>' for character '<bracket>' at position <index> of sequence: <sequence>"
   ["583"]="Error: SequenceParser can't read labeled sequences yet: <sequence>"
   ["584"]="Error: sequence graph not fully connected"
   ["585"]="Did not find this Element in the list of atomic Elements: <element>"
   ["586"]="Error: missing atomic mass for element: <element>"
   ["587"]="Error: amino acid not found in metadata: <name>"
   ["588"]="error: different number of conformers in linkage: <linkage_details>"
   ["589"]="error: conformers have different weight in linkage: <linkage_details>"
   ["590"]="Two residues passed into findResidueLink that have no connection atoms."
   ["591"]="missing dihedrals or metadata in residue linkage: <linkage_details>"
   ["592"]="Error: Unknown rotamer type: <type>"
   ["593"]="Error: required parent residue removed by random chance. Check sequence definition"
   ["594"]="Error: could not parse conect id: <line>"
   ["595"]="Error: conect row atom id not found: <line>"
   ["596"]="PdbFile constructor could not open this file: <pdbFilePath>"
   ["597"]="Prep file exists but couldn't be opened."
)
## File locations relative to the GLYCAM_Delegator_Docker root directory.
Source_File_and_Lines=(
   ["571"]="64 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["572"]="111 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["573"]="133 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["574"]="146 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["575"]="202 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["576"]="268 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["577"]="322 : deps/gems/gmml2/src/glycoprotein/glycoproteinCreation.cpp"
   ["578"]="207 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["579"]="211 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["580"]="215 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["581"]="223 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["582"]="229 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["583"]="412 : deps/gems/gmml2/src/sequence/sequenceParser.cpp"
   ["584"]="357 : deps/gems/gmml2/src/sequence/sequenceManipulation.cpp"
   ["585"]="314 : deps/gems/gmml2/src/metadata/elements.cpp"
   ["586"]="244 : deps/gems/gmml2/src/metadata/elements.cpp"
   ["587"]="272 : deps/gems/gmml2/src/metadata/aminoAcids.cpp"
   ["588"]="133 : deps/gems/gmml2/src/CentralDataStructure/residueLinkage/residueLinkageCreation.cpp"
   ["589"]="145 : deps/gems/gmml2/src/CentralDataStructure/residueLinkage/residueLinkageCreation.cpp"
   ["590"]="205 : deps/gems/gmml2/src/CentralDataStructure/residueLinkage/residueLinkageCreation.cpp"
   ["591"]="294 : deps/gems/gmml2/src/CentralDataStructure/residueLinkage/residueLinkageCreation.cpp"
   ["592"]="41 : deps/gems/gmml2/src/CentralDataStructure/residueLinkage/residueLinkageFunctions.cpp"
   ["593"]="360 : deps/gems/gmml2/src/carbohydrate/carbohydrate.cpp"
   ["594"]="37 : deps/gems/gmml2/src/fileType/pdb/pdbFile.cpp"
   ["595"]="43 : deps/gems/gmml2/src/fileType/pdb/pdbFile.cpp"
   ["596"]="225 : deps/gems/gmml2/src/fileType/pdb/pdbFile.cpp"
   ["597"]="33 & 52 : deps/gems/gmml2/src/fileType/prep/prepFile.cpp"
)
## Using this array
##
##    Use 'grep -E' to get the equivalent of this:
## grep -E "userSelection \([^)]+\) for residue to glycosylate is incorrect format\. Must be chain_residueNumber_insertionCode"
Error_Grep_Strings=(
   ["571"]="userSelection \([^)]+\) for residue to glycosylate is incorrect format\. Must be chain_residueNumber_insertionCode"
   ["572"]="Did not find a C1 or C2 with a foreign neighbor in residue: .+, thus no anomeric atom was found\."
   ["573"]="Reducing residue and aglycone requested for Carbohydrate with name .+, but it doesn't have more than 1 residue"
   ["574"]="Problem creating glycosylation site\. The amino acid requested: .+ has name \([^)]+\) that isn't supported"
   ["575"]="Error: atom '[^']+' not found in residue .+ with atoms:"
   ["576"]="Error: Did not find a residue with id matching .+"
   ["577"]="Error: found more than 1 linkage to aglycone in .+"
   ["578"]="Error: sequence is empty:>>>.*<<<"
   ["579"]="Error: the cake is a lie:>>>.*<<<"
   ["580"]="Error: sequence contains a space:>>>.*<<<"
   ["581"]="Error: sequence cannot contain this:'[^']+':>>>.*<<<"
   ["582"]="Did not find corresponding '[^']+' for character '[^']+' at position [0-9]+ of sequence:"
   ["583"]="Error: SequenceParser can't read labeled sequences yet: .+"
   ["584"]="Error: sequence graph not fully connected"
   ["585"]="Did not find this Element in the list of atomic Elements: .+"
   ["586"]="Error: missing atomic mass for element: .+"
   ["587"]="Error: amino acid not found in metadata: .+"
   ["588"]="[Ee]rror: different number of conformers in linkage: .+"
   ["589"]="[Ee]rror: conformers have different weight in linkage: .+"
   ["590"]="Two residues passed into findResidueLink that have no connection atoms\."
   ["591"]="missing dihedrals or metadata in residue linkage: .+"
   ["592"]="Error: Unknown rotamer type: .+"
   ["593"]="Error: required parent residue removed by random chance\. Check sequence definition"
   ["594"]="Error: could not parse conect id: .+"
   ["595"]="Error: conect row atom id not found: .+"
   ["596"]="PdbFile constructor could not open this file: .+"
   ["597"]="Prep file exists but couldn't be opened\."
)
#
##
#  One grep string to check them all at once
ALL_ERROR_GREP="userSelection \([^)]+\) for residue to glycosylate is incorrect format|Did not find a C1 or C2 with a foreign neighbor|doesn't have more than 1 residue|isn't supported\. Currently you can glycosylate|not found in residue .+ with atoms:|Did not find a residue with id matching|found more than 1 linkage to aglycone|sequence is empty:>>>|the cake is a lie:>>>|sequence contains a space:>>>|sequence cannot contain this:'[^']+':>>>|Did not find corresponding '[^']+' for character '[^']+' at position|SequenceParser can't read labeled sequences yet|sequence graph not fully connected|Did not find this Element in the list of atomic Elements|missing atomic mass for element|amino acid not found in metadata|[Ee]rror: different number of conformers in linkage|[Ee]rror: conformers have different weight in linkage|no connection atoms\.|missing dihedrals or metadata in residue linkage|Unknown rotamer type|required parent residue removed by random chance|could not parse conect id|conect row atom id not found|PdbFile constructor could not open this file|Prep file exists but couldn't be opened" 
## The following is an example use
#if grep -c -E \
#  "userSelection \([^)]+\) for residue to glycosylate is incorrect format|Did not find a C1 or C2 with a foreign neighbor|doesn't have more than 1 residue|isn't supported\. Currently you can glycosylate|not found in residue .+ with atoms:|Did not find a residue with id matching|found more than 1 linkage to aglycone|sequence is empty:>>>|the cake is a lie:>>>|sequence contains a space:>>>|sequence cannot contain this:'[^']+':>>>|Did not find corresponding '[^']+' for character '[^']+' at position|SequenceParser can't read labeled sequences yet|sequence graph not fully connected|Did not find this Element in the list of atomic Elements|missing atomic mass for element|amino acid not found in metadata|[Ee]rror: different number of conformers in linkage|[Ee]rror: conformers have different weight in linkage|no connection atoms\.|missing dihedrals or metadata in residue linkage|Unknown rotamer type|required parent residue removed by random chance|could not parse conect id|conect row atom id not found|PdbFile constructor could not open this file|Prep file exists but couldn't be opened" ${GP_Log} ; then
#    echo "Known Glycoprotein Builder domain error detected!"
#fi
