#!/usr/bin/env bash
##############################################################################################################
#
# This script provides error messages generated by child processes at runtime. 
#
# The name of a script containing the error information must be given as an argument.
#
# The following locations must also be passed to this script as arguments. See below for details.
# The locations must be visible inside the container.
#
#       ${read_me}   :  Log file possibly containing error messages
#       ${write_me}  :  Log file where results should be written if there are any
#                       This file will not be created if there are no error messages
#                       !!! The path to this file must already exist!
#
# The following might also be generated if you use the procedure below and if there is a problem 
# with running this script:
#
#       ${write_me}.stderr  :  Standard error (if any) from the call to this script.
#                              It will be up to the calling function to remove this file if it is
#                              empty or should be removed for some other reason.
#
# Error messages generated here are intended for use at runtime will include the following information:
#
#       Error_Numbers
#       Error_Briefs
#       Error_Meanings
#
# How those get used will depend on the code using them.
#
# Multiple Errors
#
#     If multiple errors are detected, the Error Number is '299'. The individual errors will be written
#     to the Error_log.txt file in the project directory.
#
#########################################
#
# How to use this script
#
# 1. Create a mapfile to contain the results:
#
#    the_db_file="/sysetc/wrapper_error_db_file.bash"    # replace with the actual file
#    read_me="/path/to/the/work/dir/log.file"            # from inside the container
#    write_me="/path/to/project/dir/error_logs/log.file" # from inside the container
#
#    # note .............. v v  both of these arrows are needed.
#    mapfile -t error_data < <( /sysetc/build_error.bash \
#    "${the_db_file}" \
#    "${read_me}" \
#    "${write_me}" \
#    2>> "${write_me}.stderr" )
#
#
#    # You can do it all on one line, if you prefer:
# mapfile -t error_data < <( /sysetc/build_error.bash "${the_db_file}" "${read_me}" "${write_me}" 2>> "${write_me}.stderr" )
# 
# 2. Check **IMMEDIATELY** after the mapfile line above for the return
#
#       ## ${PIPESTATUS[0]} is the return values for build_error.bash 
#       ## ${PIPESTATUS[1]} is for the mapfile creation
#       script_exit_code="${PIPESTATUS[0]}"
#
# 3. Check if the script failed
#
#       if (( script_exit_code != 0 )); then
#           echo "Build error reporting script failed with exit code: $script_exit_code"
#           echo "If any error message (from the script) was returned it will be found here:"
#           echo "${write_me}.stderr"
#       else
#           if [ -e "${write_me}.stderr" ] ; then
#               rm "${write_me}.stderr"
#           fi
#       fi
#
# 4. Accessing the results is easy.
#
#       echo "the error number is  :  ${error_data[0]}"
#       echo "the error brief is   :   ${error_data[1]}"
#       echo "the error meaning is : ${error_data[2]}"
#
##############################################################################################################

if [ -z "${1}" ] ; then
	echo "256"
	echo "Script cannot execute"
	echo "The path to the error database file must be provided." 
	exit 1
fi
if [ -z "${2}" ] ; then
	echo "256"
	echo "Script cannot execute"
	echo "The path to the file that might contain errors must be provided." 
	exit 1
fi
if [ -z "${3}" ] ; then
	echo "256"
	echo "Script cannot execute"
	echo "The path to the file that should contain error reports must be provided." 
	exit 1
fi

Read_From="${2}"
Write_To="${3}"

source ${1}

Number_of_Errors="$( grep -c -E "${ALL_ERROR_GREP}" ${Read_From} )"

#echo "The Number of Errors is >>>${Number_of_Errors}<<<"

if [ "${Number_of_Errors}" -eq "0" ] ; then
	echo "0"
	echo "No Errors Found"
	echo "No error log will be written."
	exit 0
fi

touch "${Write_To}" 
result="$?"
if [ "${result}" -ne "0" ] ; then
	echo "256"
	echo "Script cannot execute"
	echo "Unable to write to the output file >>>${Write_To}<<<." 
	exit "${result}"
fi

tries=0
errors_found=0
error_number="${Min_Err_Number}"


while [ "${error_number}" -le "${Max_Err_Number}" ] ; do
        if grep -q -E "${Error_Grep_Strings[${error_number}]}" ${Read_From} ; then
        	echo """---
Error number ${error_number} detected: ${Error_Briefs[${error_number}]}
${Error_Meanings[${error_number}]}
The original error text from the log file follows.""" >> "${Write_To}"
                grep -E "${Error_Grep_Strings[${error_number}]}" ${Read_From} >> "${Write_To}"
		if [ "${Number_of_Errors}" -eq "1" ] ; then
			echo "${error_number}"
			echo "${Error_Briefs[${error_number}]}"
			echo "${Error_Meanings[${error_number}]}"
			exit 0
		fi
		errors_found="$((errors_found+1))"
	fi
        error_number="$((error_number + 1))"
	tries="$((tries+1))"
	if [ "${tries}" -gt 100 ] ; then
		echo "256"
		echo "Error parsing failure"
		echo "Something went wrong trying to grep for errors."
		exit 1
	fi
done

echo "299"
echo "Multiple Errors Found"
echo "See ${Write_To} for details"
exit 0
