#!/usr/bin/env bash

## This should rightly be in Python, but for now it is in BASH
## OTOH, BASH is much more portable.

source /sysetc/settings.bash
source /sysetc/functions.bash
DATENOW="$(date +%Y-%m-%d-%H-%M)"
ScriptName="$(basename ${0})"

declare -a RequiredHeaders  ## These are ordered as they appear in the USAGE statement
RequiredHeaders=("pdb_id" "amino_acid_chain" "glycosylation_site_pdb" "sequence_glycam_iupac")
declare -a ParsedHeaders  ## These are in the order of the treated input file
ParsedHeaders=("project_id" "uniprotkb_canonical_ac" "pdb_id" "amino_acid_chain" "glycosylation_site_pdb" "insertion_code" "amino_acid_pdb" "glycosylation_type" "sequence_glycam_iupac")

# The values will be overwritten. What is shown here is documentation.
#    Each Key is a key in the JSON schema
#    Each Value is either:
#        - One of the ParsedHeaders (see lists above)
#        - A brief description of a field not in ParsedHeaders
declare -A jsonMainHeaders
jsonMainHeaders=(
	["givenName"]="project_id"
	["rcsb_id"]="pdb_id"
	["pUUID"]="ProjectUUID from GEMS"
	["glycan_mappings"]="list of glycositeData"
	)
declare -A glycositeData
glycositeData=(
	["Chain"]="amino_acid_chain"
	["ResidueNumber"]="glycosylation_site_pdb"
	["InsertionCode"]="insertion_code"
	["Sequence"]="sequence_glycam_iupac"
	["Tags"]="available but not used here"
	)
declare -a glycositeDataList
export glycositeDataList=() # list of JSON-Formatted glycositeData -- see printarrJSON in sysetc/functions.bash
theArrayString=""
theOptionsString=""

##########################################################
#
# If there are no resolved PDBs, but there are some sites that always resolved, set a boolean.
RescueResolvableSites="False" 
MaxRescueCycles="1" ## make this configurable in the futire
RescueCycles="0" 
#
##########################################################

#######################################
##          I/O And Usage Documentation
#######################################

USAGE="""
USAGE:

   ${ScriptName} <Input-File>

Generate a set of PDB files containing 3D structures of glycoproteins based on a list of PDB IDs, linkage sites, and sequences.

    Input-File format: 
   
        Comma-separated table containing columns with the parsed headers, in any order. 
 
          -  !! The first line must contain headers.
          -  If a header entry starts with a hash ('#'), the hash will be removed before processing. 

	Parsed headers: 

	    -  Headers can be in any order. Non-parsed headers can be present.
	    -  Parsed headers must be spelled as shown below.
	    -  For convenience below, parsed headers are listed in order of requirement status.

            (*) : required column
            (!) : possibly required column
            (+) : recommended column
            (-) : optional column
        
            pdb_id (*) : The PDB ID used in the wwPDB at rcsb.org.

	    amino_acid_chain (*) : The Chain ID (typically a capital letter) for the chain containing the residue to glycosylate.

            glycosylation_site_pdb (*) : The Residue Number of the residue to be glycosylated.

            sequence_glycam_iupac (*) : The glycan to place at the site in GLYCAM Condensed IUPAC format.

	    insertion_code (!) : The Insertion Code (IC) of the residue to be glycosylated. Might be required.
	      -  If none of your residues have insertion codes, this column can be omitted.
	      -  If your residues contain insertion codes, they MUST BE GIVEN. The residue cannot be uniquely
	         identified without the IC.
		 -  You can add the IC to the end of the residue number. For example, residue 85 with IC 'E' can be written '85E'.
		 -  Here is a nice explanation of ICs:
		    https://bioinformatics.stackexchange.com/questions/11587/what-is-the-aim-of-insertion-codes-in-the-pdb-file-format

            start_aa || amino_acid_pdb (+) : The PDB-style three-letter-code for the amino acid to glycosylate. Recommended.
              -  Header can have either name. It will be 'amino_acid_pdb' in outputs.
              -  This is not used. If you get an error message about the site, it might be useful to have this handy.

            glycosylation_type (+) : The type of linkage to the amino acid. Recommended.
              -  This is not used. If you get an error message about the site, it might be useful to have this handy.

            project_id (-) : Preferred key to identify a glycoprotein build. Also called the Basename. Optional.
              -  Keep it *NIX friendly (e.g., no spaces, asterisks, etc.)
              -  Use only the project_id you want for output files, no 'pdb' suffix - or your files will be named 'project_id.pdb.pdb'
              -  This name will also be used for error outputs, histories, results db, etc.
              -  IF MISSING - the basename/project_id will be the pdb_id. See also notes on filenames and uniprotkb_canonical_ac.

            uniprotkb_canonical_ac (-) : Uniprot Knowledgebase Canonical Accession identifier. 
              -  If this is present, and if the project_id is NOT present, then the project_id will be: 'uniprotkb_canonical_ac'_'pdb_id'
	         -  For example, if uniprotkb_canonical_ac='P13671-1' and pdb_id='3T5O', project_id='P13671-1_3T5O'
	      -  If the project_id column is populated, that project_id will not be overwritten.

	Notes on input file parsing:

	  -  Input errors include:
	     -  Required Headers columns are missing. 
	        -  This will cause the entire process to stop. No lines will be processed.
	     -  Duplicate lines : The associated project_id will not be processed. 
	     -  More than one pdb_id per uniprotkb_canonical_ac : The relationship must be 1:1. The associated project_id will not be processed.
	        - If you want to have multiple pdb_id's associated with a single uniprotkb_canonical_ac, you must use the project_id field to
		  separate them into distinct projects.
	     -  The presence of a project_id column, but the column contains one or more entries that are empty or 'null'.
	        -  This will cause the entire process to stop. No lines will be processed.
	  -  The lines in the file will be sorted. 
	     -  This simplifies finding other input errors.
	     -  It also means that the order of the outputs will be sorted by the first Parsed Header column in the input.
	  -  The modified data are always written to the Treated_Input subdirectory.
	  -  Errors and non-trivial / non-documented changes will be logged in detail.
	     -  Example : Your file contains duplicate lines.
	        -  The status log file will contain only a reference to the situation.
		-  The main log file (the 'details' log) will contain a listing of all lines that were not processed.
		   - This includes all lines associated with the project, duplicated or not.
		   - The duplicated line(s) and the number of duplicates for each line will be noted.
	  -  Documented and trivial changes will be logged only tersely.
	     -  Example : Your file contains uniprotkb_canonical_ac and pdb_id but NOT project_id:
	        -  The log files will note that the project_id is being assigned based on uniprotkb_canonical_ac and pdb_id.
		-  They will not enumerate every new project_id because those are visible in Treated_Input/.

     
        Samples of first few lines of input:

	  Minimal input file:
	    -  Note that if any glycosylation site has an insertion code as part of its name, it must be included!
	       This example does not include the insertion code.

pdb_id,amino_acid_chain,glycosylation_site_pdb,sequence_glycam_iupac
3T5O,A,17,DGlcpb1-3LFucpa1-OH
4E0S,B,17,DGlcpb1-3LFucpa1-OH
3VN4,A,115,DGlcpb1-3LFucpa1-OH
6RUR,A,65,DGlcpb1-3LFucpa1-OH
6RUR,C,65,DGlcpb1-3LFucpa1-OH
6RUR,D,18,DGlcpb1-3LFucpa1-OH
6RUR,B,18,DGlcpb1-3LFucpa1-OH

	  Input file with other columns (parsed and not parsed):

#project_id,glycosylation_type,pdb_id,my_special_column,amino_acid_chain,glycosylation_site_pdb,start_aa,sequence_glycam_iupac
my_gp_1,O-linked,3T5O,my_info,A,17,THR,DGlcpb1-3LFucpa1-OH
my_gp_2,O-linked,4E0S,my_info,B,17,THR,DGlcpb1-3LFucpa1-OH
my_gp_3,O-linked,3VN4,my_info,A,115,SER,DGlcpb1-3LFucpa1-OH
my_gp_4,O-linked,6RUR,my_info,A,65,THR,DGlcpb1-3LFucpa1-OH
my_gp_4,O-linked,6RUR,my_info,C,65,THR,DGlcpb1-3LFucpa1-OH
my_gp_4,O-linked,6RUR,my_info,D,18,THR,DGlcpb1-3LFucpa1-OH
my_gp_4,O-linked,6RUR,my_info,B,18,THR,DGlcpb1-3LFucpa1-OH

          Sample input file error: 
            -  Here, a Uniprot ID is used as the project_id. but it refers to two different PDB IDs. This will cause an error.
 
!!   #project_id,glycosylation_type,pdb_id,my_special_column,amino_acid_chain,glycosylation_site_pdb,start_aa,sequence_glycam_iupac
!!   P13671-1,38,Thr,G36855WW,O-linked,3T5O,pdb_00003t5o,A,17,38,38,THR,THR,T,DGlcpb1-3LFucpa1-OH
!!   P13671-1,38,Thr,G36855WW,O-linked,4E0S,pdb_00004e0s,B,17,38,38,THR,THR,T,DGlcpb1-3LFucpa1-OH
 
  Outputs: various files
  
    Mostly, you will be interested in: 
    - PDB files : \${OUTPUTS_DIR}/conjugate/gp/\${OUT_SUBDIR}/PDB/
    - Treated input files, if any : \${OUTPUTS_DIR}/conjugate/gp/\${OUT_SUBDIR}/Treated_Inputs

    Note that inside the Docker container:
    - INPUTS_DIR is always '/inputs/'.
    - OUTPUTS_DIR is always '/outputs/'.
    - WORK_DIR is always '/work/'.
   
    Also there are:
    - Provenance trail: \${OUTPUTS_DIR}/conjugate/gp/\$OUT_SUBDIR/provenance/
    - Build DB: \${OUTPUTS_DIR}/conjugate/gp/\$OUT_SUBDIR/${ScriptName}_DB.csv  
      - Where \"${ScriptName}\" is the name of this script.
      - This will contain sufficient information to easily determine where to find the structure's provenance.
      - This provenance info is also in the \${responseJSON} in the provenance directory, but that's not as easy to read.
      - Contents:
        - Comma-separated table of: (still TBD)

    For those who need all the details:
    - The workspace for generating the structures: \${WORK_DIR}/conjugate/gp/\${pUUID}/
      - You can find the value of \${pUUID} in the \${responseJSON} in the provenance directory.

"""

#echo "${USAGE}"  # Used when testing the usage output only.
#exit 0           #

#######################################
##   Code With Procedural Documentation
#######################################

#############################
##                  Functions
#############################

## Define the function that will write the JSON build file for the glycoprotein
write_json_build_file() {
	# $1 is the output filename
	# The array called 'jsonMainHeaders' MUST be properly populated before calling.
	#    Needs: givenName and rcsb_id

	# Generate the options section
	startnext=
	theOptionsString=""
	first="True"
	startnext=',\n'
	for option in ${GPB_Options[@]} ; do
    	if [ "${first}" == "True" ] ; then
        	tmpString="$(printf "\"%s\" : \"%s\"" "${option}" "${GPB_Options_Values[${option}]}")"
		first="False"
    	else
        	tmpString="$(printf "${startnext}\"%s\" : \"%s\"" "${option}" "${GPB_Options_Values[${option}]}")"
    	fi
    	theOptionsString="${theOptionsString} ${tmpString}"
	done


	theFile="""{
    \"entity\": {
        \"type\": \"GlycoProtein\",
	\"procedural_options\": 
	{
		\"force_serial_execution\" : \"True\",
    		\"pretty_print\" : \"True\"
	},
        \"services\":
          {
                \"${jsonMainHeaders["givenName"]}_Build\": {
                    \"type\": \"Build\",
                    \"givenName\": \"${jsonMainHeaders["givenName"]}\",
                    \"inputs\": {
                        \"rcsb_id\": \"${jsonMainHeaders["rcsb_id"]}\",
                        \"glycan_mappings\": [
${theArrayString}
                        ]
                    },
		    \"options\":{
${theOptionsString}
	            }
                }
          }
    },
    		\"prettyPrint\" : \"True\"
}
""" 

echo "Writing JSON input for generating structure files to: ${1}" >> $LOGFILE
echo "${theFile}" > ${1}

} # closes the function - is not part of the json

process_the_build()
{
	## 
	# This function processes an individual build or a rescue build.
	# To this function those are identical processes
	##

	##
	# Some debugging options - uncomment temporarily if needed.
	echo "This is the glycosite data list after-loop."
	echo """${glycositeDataList[@]}"""
	echo "accessing a certain value:"
	echo """${glycositeDataList[3]}"""
	echo "here is that data accessed via integer"
	echo "sitecount is ${sitecount}"
	##

        ##
	# Build input for the part of the JSON that holds glycosite info
	theArrayString=""
	i="0"
	while [ "${i}" -lt "${sitecount}" ] ; do
               	if [ "${i}" == "0" ] ; then
			tmpString="${glycositeDataList[$i]}"
               	else
			tmpString="$(printf "${startnext} %s " "${glycositeDataList[$i]}")"
               	fi
		theArrayString="${theArrayString} ${tmpString}" 
		#echo "For ${i} it is : ${glycositeDataList[${i}]}"
		i="$((i+1))"
	done
	#theArrayString="${theArrayString} ]"
	echo "The array string is"
	echo """${theArrayString}"""
	jsonMainHeaders["glycan_mappings"]="${theArrayString}"
	#echo "json main headers are:"
	#echo """${jsonMainHeaders[@]}"""
	##

	##
	# Build the file to be delegated
	jsonRequestFileName="${OutputDir}/provenance/${thisProjectID}_Build_Request.json"
	if [ "${RescueResolvableSites}" == "True" ] ; then
		jsonRequestFileName="${OutputDir}/provenance/${thisProjectID}_rescue_Build_Request.json"
	fi
	write_json_build_file "${jsonRequestFileName}"
	##

	##
	# Build the file to be delegated, delegate it, and save the results.
	# If all that worked, call the script that manages output
	echo "[INFO] : $(date) : Starting PDB file generation for Project ID: ${thisProjectID}." >> ${STATUSFILE}
	echo "Starting PDB file generation for Project ID: ${thisProjectID}." >> ${LOGFILE}
	jsonResponseFileName="${OutputDir}/provenance/${thisProjectID}_Build_Response.json"
	if [ "${RescueResolvableSites}" == "True" ] ; then
		jsonResponseFileName="${OutputDir}/provenance/${thisProjectID}_rescue_Build_Response.json"
	fi
	jsonResponse="$(delegate ${jsonRequestFileName} 2>&1)"
	result="$?"
	if [ ${result} != "0" ] ; then
		echo "[ERROR] : $(date) : Build failed for Project ID: ${thisProjectID}." >> ${STATUSFILE}
		echo "Build failed for Project ID: ${thisProjectID}." >> ${LOGFILE}
		echo """The response returned, if any, appears between the rows of equals signs below.
===============================================================================
${jsonResponse}
===============================================================================
""" >> ${LOGFILE}
	else : 
		echo "[INFO] : $(date) : Build completed for Project ID: ${thisProjectID}." >> ${STATUSFILE}
		echo "Build completed for Project ID: ${thisProjectID}." >> ${LOGFILE}
		#export TEST="True"
	#	typical JSON file location:  /work/conjugate/gp/${thisProjectID}/logs/response.json 
		echo """${jsonResponse}
""" > "${jsonResponseFileName}"
		## 
		# Mange the output
		echo "about to manage the output"
		. /sysetc/GlycoProtein_manage_build_output.bash 
	fi
} # close process_the_build


###############################################################################
# The processing of the input file starts here
###############################################################################
#############################
##           Setup And Checks
#############################

## Check that an input file is specified on the command line
##
### - If not, print a statement and exit 1.
if [ -z "${1}" ] ; then
	echo "${USAGE}"
	print_error_and_exit "Command-line argument required. Exiting."
else
	InputFile="${1}"
fi

## Set I/O settings 
##
### - Read from ./${AUTOGENERATED_FILE_PREFIX}_config.sh and SessionSettings.bash in /programs/share/
### - Needs:
###   - $OUT_SUBDIR
###   - $OVERWRITE_OUTPUT
### - Record session/config info in provenance directory per date-time.
if [ -e "/sysetc/${AUTOGENERATED_FILE_PREFIX}_config.bash" ] ; then
	echo "sourcing config: /sysetc/${AUTOGENERATED_FILE_PREFIX}_config.bash"
	source "/sysetc/${AUTOGENERATED_FILE_PREFIX}_config.bash"
fi
if [ -e "/programs/share/SessionSettings.bash" ] ; then
	echo "sourcing session settings: /programs/share/SessionSettings.bash" 
	source "/programs/share/SessionSettings.bash"
fi
if [ -z "${OUT_SUBDIR}" ] ; then
	print_error_and_exit "OUT_SUBDIR not specified. Exiting. Re-run script with no arguments if you need to see the USAGE."
fi
OutputDir="/outputs/conjugate/gp/${OUT_SUBDIR}"
GoodPdbDir="${OutputDir}/PDB"
#BadPdbDir="${OutputDir}/PDB/rejected" # since we have multiple samples now, this is confusing
SamplesGoodPdbDir="${OutputDir}/PDB/all_samples"
SamplesBadPdbDir="${OutputDir}/PDB/all_samples/rejected"
BadPdbDir="${SamplesBadPdbDir}" 
SummariesDir="${OutputDir}/PDB/all_samples/summaries"
mkdir -p "${OutputDir}/logs" || print_error_and_exit "Unable to create directory: ${OutputDir}/logs. Exiting."
mkdir -p "${OutputDir}/provenance" || print_error_and_exit "Unable to create directory: ${OutputDir}/provenance. Exiting."
#mkdir -p "${BadPdbDir}" || print_error_and_exit "Unable to create directory(ies): ${BadPdbDir}. Exiting."
mkdir -p "${SamplesBadPdbDir}" || print_error_and_exit "Unable to create directory(ies): ${SamplesBadPdbDir}. Exiting."
mkdir -p "${SummariesDir}" || print_error_and_exit "Unable to create directory(ies): ${SummariesDir}. Exiting."
mkdir -p "${OutputDir}/Treated_Inputs" || print_error_and_exit "Unable to create directory: ${OutputDir}/Treated_Inputs. Exiting."
export LOGFILE="${OutputDir}/logs/details_${DATENOW}_${ScriptName}.log"
export LOGFILE_RELATIVE="logs/details_${DATENOW}_${ScriptName}.log"
export STATUSFILE="${OutputDir}/logs/status_${DATENOW}_${ScriptName}.log"
export STATUSFILE_RELATIVE="logs/status_${DATENOW}_${ScriptName}.log"
dbOutputFile_RELATIVE="${ScriptName}_DB.csv"
if [ "${DATE_BUILD_DATABASE}" == "True" ] ; then
        dbOutputFile_RELATIVE="${DATENOW}_${ScriptName}_DB.csv"
fi
dbOutputFile="${OutputDir}/${dbOutputFile_RELATIVE}"
touch "${dbOutputFile}" || print_error_and_exit "Unable to create build database: ${dbOutputFile}. Exiting."
echo "Details file for ${ScriptName} begun on $(date)" > ${LOGFILE}
echo "[INFO] : $(date) : Status file for ${ScriptName} begun" > ${STATUSFILE}
if [ -z "${OVERWRITE_OUTPUT}" ] ; then
	echo "OVERWRITE_OUTPUT not found in input files. Using 'False'." >> ${LOGFILE}
fi
echo "[INFO] : $(date) : Build DB filename: ${dbOutputFile_RELATIVE}" >> $STATUSFILE
echo "Build DB filename, relative to build directory: ${dbOutputFile_RELATIVE}" >> $LOGFILE
##  - project_id , uniprotkb_canonical_ac , pdb_id , pUUID , Result , Date_Time , Code , Brief , Meaning , Text , Removed_Site , Note
Prefix="project_id,uniprotkb_canonical_ac,pdb_id,pUUID" # these parts should not change once set for a specific build - see below
echo "#${Prefix},Result,Date_Time,Code,Brief,Meaning,Text,Removed_Site,Note" > "${dbOutputFile}"


#############################
##                  Procedure
#############################

## Read in line 1 of the input file:
declare -a inputFileHEADERS
tmphead="$(head -n 1 ${InputFile})"
IFS=, read -ra inputFileHEADERS <<< "${tmphead}"

## Ensure that all the RequiredHeaders are present
# RequiredHeaders="pdb_id amino_acid_chain glycosylation_site_pdb sequence_glycam_iupac"
allthere="True"
for rheader in ${RequiredHeaders[@]} ; do 
	if [[ "${inputFileHEADERS[@]}" != *"${rheader}"* ]] ; then
		allthere="False"
	fi
done
if [ "${allthere}" == "False" ] ; then
	echo "[ERROR] : $(date) : Required Headers not found in input file" | tee -a ${STATUSFILE}
	echo "[ERROR] : $(date) : Required Headers not found in input file" > ${LOGFILE}
	echo "These are the Required Headers:" | tee -a ${LOGFILE}
	echo "${RequiredHeaders[@]}" | tee -a ${LOGFILE}
	echo "These are your headers:" | tee -a ${LOGFILE}
	echo "${inputFileHEADERS[@]}" | tee -a ${LOGFILE}
	print_error_and_exit "All required headers are not present in the input file."
fi


# If 'start_aa' was used rather than 'amino_acid', change the value in
declare -a outHEADERS
if [[ "${inputFileHEADERS[@]}" == *"start_aa"* ]] ; then
	echo "[INFO] : $(date) : start_aa was found - changing it to the standard 'amino_acid_pdb' for final output" | tee -a $LOGFILE
        outHEADERS=( "${inputFileHEADERS[@]/start_aa/amino_acid_pdb}" )
	useStartAA="True"
fi

## Note which ParsedHeaders are present in the user inputs
# ParsedHeaders="project_id uniprotkb_canonical_ac pdb_id amino_acid_chain glycosylation_site_pdb insertion_code amino_acid_pdb glycosylation_type project_id sequence_glycam_iupac"
declare -A ParsedHeadersPresent
declare -a outputTreatedHEADERS
for pheader in ${ParsedHeaders[@]} ; do 
	if [[ "${outHEADERS[@]}" == *"${pheader}"* ]] ; then
		ParsedHeadersPresent["${pheader}"]="True"
		outputTreatedHEADERS+=("${pheader}")
	else
		ParsedHeadersPresent["${pheader}"]="False"
	fi
done

## Determine what to use for the 'project_id'.
if [[ "${inputFileHEADERS[@]}" != *"project_id"* ]] ; then
	echo "[INFO] : $(date) : Column 'project_id' not found in input file." | tee -a $STATUSFILE
	ProjectIDBase='pdb_id'
	if [[ "${inputFileHEADERS}" == *"uniprotkb_canonical_ac"* ]] ; then
		ProjectIDBase='uniprotkb_canonical_ac'
		echo "[INFO] : $(date) : Using uniprotkb_canonical_ac and pdb_id to form project_id." | tee -a $STATUSFILE
	else
		echo "[INFO] : $(date) : Using pdb_id as project_id." | tee -a $STATUSFILE
	fi
else
	ProjectIDBase='project_id'
	echo "[INFO] : $(date) : A column for 'project_id' is found in the input file." | tee -a $STATUSFILE
	# $ csvstat -c project_id --null new.csv
	# True  ## True if there are null entries for project_id in the incoming file
	nullPIDs="$(csvstat -c project_id --null ${InputFile})"
	if [ "${nullPIDs}" == "True" ] ; then
		echo "[ERROR] : $(date) : The 'project_id' column contains empty or null entries. Exiting." | tee -a $STATUSFILE
		echo "[ERROR] : $(date) : Here are stats regarding empty/null entries for project_id:" | tee -a $LOGFILE
		csvstat -c project_id "${InputFile}" | tee -a $LOGFILE
		print_error_and_exit "project_id entries cannot be null or empty"
	fi
fi

## 
## Generate the Treated Input file
##
##
## First, generate a temporary version of the Treated File that contains only the Parsed Headers
#
# Make a list of the parsed headers is in the input file so that they can be handed to csvcut
first="true"
cutCols=""
for pheader in ${ParsedHeaders[@]} ; do 
	if [ "${ParsedHeadersPresent["${pheader}"]}" == "True" ] ; then
		if [ "${useStartAA}" == "True" ] ; then
			if [ "${pheader}" == "amino_acid_pdb" ] ; then
				pheader="start_aa"
			fi
		fi
		if [ "${first}" == "true" ] ; then
			cutCols="${pheader}"
			first="false"
		else
			cutCols="${cutCols},${pheader}"
		fi
	fi
done
#
# Use csvcut to extract the columns into a temporary file
#    csvcut -c column_c,column_a,column_z data.csv > new.csv
TmpUUID="$(uuidgen -r)"
TmpTreatedFileName="${TmpUUID:0:5}.csv"
TmpTreatedFilePath="/tmp"
if [ "${KEEP_TEMPORARY_FILES}" == "True" ] ; then
	TmpTreatedFilePath="${OutputDir}/logs"
	echo "[INFO] : $(date) : The temporary (and intermediate) Treated_Input file will be saved in:" | tee -a $LOGFILE
	echo "[INFO] : $(date) :     ${TmpTreatedFilePath}" | tee -a $LOGFILE
fi
TmpTreatedFileOut="${TmpTreatedFilePath}/${TmpTreatedFileName}"
COMMAND="csvcut -c ${cutCols} ${InputFile} > ${TmpTreatedFileOut}"
rclr "Writing a temporary input file containing Parsed Headers in a standard order" "${COMMAND}" "Temporary treated input file write"
if [ "${useStartAA}" == "True" ] ; then
	COMMAND="sed -i '1s/start_aa/amino_acid_pdb/' ${TmpTreatedFileOut}"
	rclr "Changing start_aa in the first temporary file to amino_acid_pdb." "${COMMAND}" "Enforce use of amino_acid_pdb header"
fi
#
## Sort the file so that various statistics can be generated
#
# Use csvsort to avoid using tail (but write in a 'large file' feature if that becomes a problem)
TmpTreatedFileNameSorted="${TmpTreatedFileName}_sorted"
TmpTreatedFileOutSorted="${TmpTreatedFilePath}/${TmpTreatedFileNameSorted}"
COMMAND="csvsort ${TmpTreatedFileOut} > ${TmpTreatedFileOutSorted}"
rclr "Sorting the temporary input file." "${COMMAND}" "Temporary treated input file sort"
#
## Count and list the non-unique lines.
#
TmpDuplicatesFileName="${TmpTreatedFileName}_duplicates"
TmpDuplicatesFileOut="${TmpTreatedFilePath}/${TmpDuplicatesFileName}"
COMMAND="cat ${TmpTreatedFileOutSorted} | uniq -cd > ${TmpDuplicatesFileOut}"
rclr "Checking for duplicate entries in the input file." "${COMMAND}" "Duplicate entries check"
#  cat some_file_with_duplicates.csv | sort | uniq -cd  ## not exactly the workflow here, but shows the output
#       3 P00451-1,2137,Asn,G22768VO,N-linked,6MF0,pdb_00006mf0,A,1253,2137,2137,ASN,ASN,N,DManpa1-3[DManpa1-6]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
#       3 P00451-1,2137,Asn,G56014GC,N-linked,6MF0,pdb_00006mf0,B,1253,2137,2137,ASN,ASN,N,DManpa1-2DManpa1-3[DManpa1-6]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
#       3 P01023-1,396,Asn,G22573RC,N-linked,6TAV,pdb_00006tav,A,396,396,396,ASN,ASN,N,DManpa1-6DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
#       3 P01023-1,55,Asn,G22573RC,N-linked,6TAV,pdb_00006tav,A,55,55,55,ASN,ASN,N,DManpa1-6DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
numDups="$(wc -l ${TmpDuplicatesFileOut} | cut -d ' ' -f1)"
result="$?"
if [ "${result}" != "0" ] ; then
	print_error_and_exit "Unable to count the number of duplicate entries in the sorted temporary file."
fi
#
# Copy the current result to a temporary 'final' file containing user-supplied input. If there are dups, it is not really final yet.
TmpFinalFileOut="${TmpTreatedFilePath}/${TmpTreatedFileName}_final_user_directives"
cp "${TmpTreatedFileOutSorted}" "${TmpFinalFileOut}"
#
## If there are duplicate lines, record that info in provenance and remove those lines from the sorted temporary input.
#
if [ "${numDups}" != "0" ] ; then
	COMMAND="cp ${TmpDuplicatesFileOut} ${OutputDir}/provenance/User_Input_Duplicates.txt"
	rclr "Duplicate lines found. Copying their stats to provenance." "${COMMAND}" "Recording duplicates info."
	#
	## Remove any project containing duplicated lines
	# 
	# Read the project info from duplicates record 
	# For each line, take the second entry (dealing with mix of commas and spaces as separators)
	# Then remove all lines beginning with that string from the interim treated input file.
	#
	# Loop over the input file contents
       	while IFS=, read -ra line; do
               	# get the second entry (the first is the duplicates count)
		# ...but there is complication by a mix of separating characters (space, comma)
               	# echo "the line is:"
               	# echo "${line[@]}"
               	sedTarget="${line[0]##* }"
               	COMMAND="sed -i '/^${sedTarget}/d' ${TmpFinalFileOut}"
		rclr "Removing all requests related to project ${sedTarget} with duplicate directive lines." "${COMMAND}" "${sedTarget} duplicates removal"
	done < "${TmpDuplicatesFileOut}"
fi
#
## If there is not a project_id column, and there is a uniprot ID, ensure that there is a 1:1 correspondence between uniprot ID and pdb_id
if [[ "${outputTreatedHEADERS[@]}" != *"project_id"* ]] ; then
	if [[ "${outputTreatedHEADERS[@]}" == *"uniprotkb_canonical_ac"* ]] ; then
		TmpUniPDBTestOut="${TmpTreatedFilePath}/${TmpTreatedFileName}_non-unique_uniprot_pdb"
		# !! This only counts multiple PDBs per uniprotID. It does not count multiple uniprotIDs per PDB. 
		#    The latter does not matter to this software. If desired by users, the latter could be added.
		COMMAND="csvcut -c uniprotkb_canonical_ac,pdb_id ${TmpFinalFileOut} | csvsort | uniq | cut -d ',' -f1 | uniq -cd > ${TmpUniPDBTestOut}"
		rclr "Checking for uniprotID:pdbID not being 1:1 when project_id not specified." "${COMMAND}" "Duplicate uniprot-pdb per project check"
		numDups="$(wc -l ${TmpUniPDBTestOut} | cut -d ' ' -f1)"
		result="$?"
		if [ "${result}" != "0" ] ; then
			print_error_and_exit "Unable to count the number of duplicate entries in the sorted temporary file."
		fi
		#
		## If there are duplicate lines, record that info in provenance and remove those lines from the sorted temporary input.
		if [ "${numDups}" != "0" ] ; then
			COMMAND="cp ${TmpUniPDBTestOut} ${OutputDir}/provenance/User_Inputs_Duplicate_Uniprot-PDB.txt"
			rclr "Duplicate lines found. Copying their stats to provenance." "${COMMAND}" "Recording duplicates info."
			#
			## Remove any project containing duplicated uniprot:pdb
       			while IFS=, read -ra line; do
               			# get the second entry (the first is the duplicates count)
				# ...but there is complication by a mix of separating characters (space, comma)
               			# echo "the line is:"
               			# echo "${line[@]}"
               			sedTarget="${line[0]##* }"
               			COMMAND="sed -i '/^${sedTarget}/d' ${TmpFinalFileOut}"
				rclr "Removing all requests related to project ${sedTarget} with duplicate PDBs." "${COMMAND}" "${sedTarget} duplicate PDBs removal"
			done < "${TmpUniPDBTestOut}"
		fi
	fi
fi
#
## Generate the final treated input file
FinalTreatedInput="${OutputDir}/Treated_Inputs/$(basename ${InputFile}).treated.csv" 
rowfirst="true"
the_uniprotkb_cannonical_ac="None"
the_pdb_id="None"
declare -a columnrow
while IFS=, read -ra columnrow; do
	#
	## Get info from and do consistency checks using the first row
	if [ "${rowfirst}" == "true" ] ; then
		if [ "${#outputTreatedHEADERS[@]}" != "${#columnrow[@]}" ] ; then
			echo "#outHeaders: ${#outputTreatedHEADERS[@]}" 
			echo "outHeaders: ${outputTreatedHEADERS[@]}" 
			echo "#columnrow: ${#columnrow[@]}" 
			echo "columnrow: ${columnrow[@]}" 
			print_error_and_exit "#outputTreatedHEADERS not equal to #columnrow in treated-input generation."
		fi
		# ProjectIDBase can be: 'uniprotkb_canonical_ac' 'project_id' 'pdb_id'
		pdbidLoc="-1"
		uniprotLoc="-1"
		numInCol="${#columnrow[@]}"
		count="0"
		while [ "${count}" -lt "${numInCol}" ] ; do
			if [ "${outputTreatedHEADERS[${count}]}" != "${columnrow[${count}]}" ] ; then
				print_error_and_exit "Entry ${count} not identical for outputTreatedHEADERS and columnrow in treated-input generation."
			fi
			#if [ "${ProjectIDBase}" != "project_id" ] ; then
			if [ "${columnrow[${count}]}" == "pdb_id" ] ; then
				pdbidLoc="${count}"
			fi
			if [ "${columnrow[${count}]}" == "uniprotkb_canonical_ac" ] ; then
				uniprotLoc="${count}"
			fi
			#fi
			count="$((count+1))"
		done
		colfirst="true"
		rowOut=""
		for pheader in ${ParsedHeaders[@]} ; do  ## this list should be equal to or longer than outputTreatedHEADERS???
			if [ "${colfirst}" == "true" ] ; then
				colfirst="false"
				separator=""
			else
				separator=","
			fi
			rowOut="${rowOut}${separator}${pheader}"
		done
		echo "${rowOut}" > "${FinalTreatedInput}"
		rowfirst="false"
		continue
	fi
	#
	## For each parsed header
	colfirst="true"
	inColCount="0"
	rowOut=""
	for pheader in ${ParsedHeaders[@]} ; do  ## this list should be equal to or longer than outputTreatedHEADERS???
		if [ "${colfirst}" == "true" ] ; then
			colfirst="false"
			separator=""
		else
			separator=","
		fi
		copymetofile=""	
		if [ "${ParsedHeadersPresent["${pheader}"]}" == "True" ] ; then
			# If we got here, but we're out of headers entries, write error and exit
			if [ "${inColCount}" == "${numInCol}" ] ; then
				print_error_and_exit "Out of present headers in generate treated-input."
			fi
			# Copy this one into the file
			copymetofile="${separator}${columnrow[${inColCount}]}"
			inColCount="$((inColCount+1))"
		else
			# If this is project_id, generate it 
			if [ "${pheader}" == "project_id" ] ; then
				tmpstring="${columnrow[${pdbidLoc}]}"
				if [ "${ProjectIDBase}" == "uniprotkb_canonical_ac" ] ; then
					tmpstring="${columnrow[${uniprotLoc}]}_${tmpstring}"
				fi
				copymetofile="${separator}${tmpstring}"
			# Else, make this a 'null' entry
			else  
				copymetofile="${separator}null"
			fi
		fi
		if [ "${colfirst}" == "true" ] ; then
			colfirst="false"
		fi
		rowOut="${rowOut}${copymetofile}"
	done
## Grab some info for the summary file
#echo "getting info for the summary file"
#echo "uniprotLoc = ${uniprotLoc}"
#echo "pdbidLoc = ${pdbidLoc}"
if [ "${uniprotLoc}" != "-1" ] ; then
	the_uniprotkb_canonical_ac="${columnrow[${uniprotLoc}]}" 
	#echo "the_uniprotkb_canonical_ac=>>>${the_uniprotkb_canonical_ac}<<<"
fi
if [ "${pdbidLoc}" != "-1" ] ; then
	the_pdb_id="${columnrow[${pdbidLoc}]}" 
	#echo "the_pdb_id=>>>${the_pdb_id}<<<"
fi

	echo "${rowOut}" >> "${FinalTreatedInput}"

done < "${TmpFinalFileOut}"

#
## Record the number of unique build requests that the treated data request (bc untreated isn't reasonable to query)
numRequestedBuilds="$(csvstat -c project_id --unique ${FinalTreatedInput})"
result="$?"
if [ "${result}" != "0" ] ; then
	print_error_and_exit "Unable to count the total number of GlycoProtein projects requested."
fi
echo "[INFO] : $(date) : A total of ${numRequestedBuilds} valid GlycoProtein projects were found." | tee -a $LOGFILE
COMMAND="tail -n +2 ${FinalTreatedInput} | cut -d ',' -f1 | uniq > ${OutputDir}/provenance/Valid_Projects_List.txt"
rclr "Generating and recording valid projects in the provenance directory." "${COMMAND}" "Valid projects list generation"
#
## Remove temporary files if not instructed to keep them
if [ "${KEEP_TEMPORARY_FILES}" != "True" ] ; then
	removeMe="${TmpTreatedFilePath}/${TmpTreatedFileName}*"
	COMMAND="rm ${removeMe}"
	rclr "Removing temporary files." "${COMMAND}" "Temporary file removal"
fi


#exit 0

##
## Build each input JSON and run the GP build
##
#
## For each valid project id
count=0
## Loop over the input file contents
while IFS=  read -r line; do
	# Reset the rescue parameters for the new project
	RescueCycles=0
	RescueResolvableSites="False"
	#
	## grep all lines associated with the project_id
	## Will look something like:
	#      P27918-1_6RUR,P27918-1,6RUR,A,65,null,THR,O-linked,DGlcpb1-3LFucpa1-OH
	#      P27918-1_6RUR,P27918-1,6RUR,B,18,null,THR,O-linked,DGlcpb1-3LFucpa1-OH
	#      P27918-1_6RUR,P27918-1,6RUR,C,65,null,THR,O-linked,DGlcpb1-3LFucpa1-OH
	#      P27918-1_6RUR,P27918-1,6RUR,D,18,null,THR,O-linked,DGlcpb1-3LFucpa1-OH
	#  The individual entries have these labels
	#      project_id,uniprotkb_canonical_ac,pdb_id,amino_acid_chain,glycosylation_site_pdb,insertion_code,amino_acid_pdb,glycosylation_type,sequence_glycam_iupac
	thisProjectID="${line}"
	echo "thisProjectID: ${thisProjectID}"
	skipme="False"
	if [ "${OVERWRITE_OUTPUT}" == "False" ] ; then
		echo "Checking for pre-existing Glycoprotein PDB"
		if [ -f "${GoodPdbDir}/${thisProjectID}.pdb" ] ; then
			echo "Found pre-existing pdb file. Skipping."
			echo "[INFO] : $(date) : Found existing PDB file for ${thisProjectID}. Not remaking." >> $STATUSFILE
			echo "Found existing PDB file for ${thisProjectID} and OVERWRITE_OUTPUT is not truthy. Not remaking." >> $LOGFILE
			echo "File exists at: ${GoodPdbDir}/${thisProjectID}." >> $LOGFILE
			skipme="True"
		fi
	fi
	if [ "${skipme}" == "True" ] ; then
		## I think this was not happening before...
		continue
	fi
	thisProjectInputs="""$(grep ^${thisProjectID} ${FinalTreatedInput} )"""
	echo "thisProjectInputs:"
	echo """${thisProjectInputs}"""
	#
	## Process the build
	#  Grab the pdb_id
	while IFS=, read -ra inputsLine ; do
		thisPDBid="${inputsLine[2]}"
		break
	done <<< "${thisProjectInputs}"
	echo "Working on PDB file:  ${thisPDBid} (= thisPDBid)"

	# Generate the needed headers (list in comment below)
	jsonMainHeaders["givenName"]="${thisProjectID}"
	jsonMainHeaders["rcsb_id"]="${thisPDBid}"
	jsonMainHeaders["pUUID"]=""
#jsonMainHeaders=(
#	["givenName"]="project_id"
#	["rcsb_id"]="pdb_id"
#	["pUUID"]="ProjectUUID from GEMS" ## Not needed here - will be assigned
#	["glycan_mappings"]="list of glycositeData"  ## generated in next step
#	)
	
	# Generate the glycositeData array (array of glycosylation sites)
#glycositeData=(
#	["Chain"]="amino_acid_chain"
#	["ResidueNumber"]="glycosylation_site_pdb"
#	["InsertionCode"]="insertion_code"
#	["Sequence"]="sequence_glycam_iupac"
#	["Tags"]="available but not used here"
#	)
#declare -A glycositeDataList
#glycositeDataList=() # list of JSON-Formatted glycositeData -- see printarrJSON in sysetc/functions.bash
	#  Sample data line
	#         0         ,   1    , 2  ,3, 4, 5  , 6 ,   7    ,       8
	#      P27918-1_6RUR,P27918-1,6RUR,B,18,null,THR,O-linked,DGlcpb1-3LFucpa1-OH

	glycositeDataList=()
	sitecount=0
        first="True"
        startnext=', '
	if [ "${PRETTY_GLYCOSYLATION_MAPPINGS}" == "True" ] ; then
                startnext=',\n'
        fi
	while IFS=, read -ra inputsLine ; do
		if [ "${inputsLine[3]}" == "null" ] ; then 
			glycositeData["Chain"]=""
		else
			glycositeData["Chain"]="${inputsLine[3]}"
		fi
		if [ "${inputsLine[4]}" == "null" ] ; then 
			glycositeData["ResidueNumber"]=""
		else
			glycositeData["ResidueNumber"]="${inputsLine[4]}"
		fi
		if [ "${inputsLine[5]}" == "null" ] ; then 
			glycositeData["InsertionCode"]=""
		else
			glycositeData["InsertionCode"]="${inputsLine[5]}"
		fi
		if [ "${inputsLine[8]}" == "null" ] ; then 
			glycositeData["Sequence"]=""
		else
			glycositeData["Sequence"]="${inputsLine[8]}"
		fi
		glycositeData["Tags"]=""
		echo "This is the glycosite data array:"
		echo """${glycositeData[@]}"""
		glySiteString="{ "
        	first="True"
        	for k in "Chain" "ResidueNumber" "InsertionCode" "Sequence" "Tags" ; do
                	if [ "${first}" == "True" ] ; then
				tmpString="$(printf "\"%s\": \"%s\"" "$k" "${glycositeData[$k]}")"
                        	first="False"
                	else
				tmpString="$(printf "${startnext}\"%s\": \"%s\"" "$k" "${glycositeData[$k]}")"
                	fi
			glySiteString="${glySiteString} ${tmpString}" 
        	done
		glySiteString="${glySiteString} }" 
		glycositeDataList[${sitecount}]="${glySiteString}"
		#echo "This is the glycosite data list in-loop."
		#echo """${glycositeDataList[@]}"""
		sitecount="$((sitecount+1))"
	done <<< "${thisProjectInputs}"

################# 
#  Where build processing used to happen:
#  From here
#################
#	#echo "This is the glycosite data list after-loop."
#	#echo """${glycositeDataList[@]}"""
#	#echo "accessing a certain value:"
#	#echo """${glycositeDataList[3]}"""
#	#echo "here is that data accessed via integer"
#	#echo "sitecount is ${sitecount}"
#	theArrayString=""
#	i="0"
#	while [ "${i}" -lt "${sitecount}" ] ; do
#               	if [ "${i}" == "0" ] ; then
#			tmpString="${glycositeDataList[$i]}"
#               	else
#			tmpString="$(printf "${startnext} %s " "${glycositeDataList[$i]}")"
#               	fi
#		theArrayString="${theArrayString} ${tmpString}" 
#		#echo "For ${i} it is : ${glycositeDataList[${i}]}"
#		i="$((i+1))"
#	done
#	#theArrayString="${theArrayString} ]"
#
#	echo "The array string is"
#	echo """${theArrayString}"""
#	jsonMainHeaders["glycan_mappings"]="${theArrayString}"
#	#echo "json main headers are:"
#	#echo """${jsonMainHeaders[@]}"""
#	jsonRequestFileName="${OutputDir}/provenance/${thisProjectID}_Build_Request.json"
#	write_json_build_file "${jsonRequestFileName}"
#	COMMAND="delegate ${jsonRequestFileName}"
#	echo "[INFO] : $(date) : Starting PDB file generation for Project ID: ${thisProjectID}." >> ${STATUSFILE}
#	echo "Starting PDB file generation for Project ID: ${thisProjectID}." >> ${LOGFILE}
#	jsonResponseFileName="${OutputDir}/provenance/${thisProjectID}_Build_Response.json"
#	jsonResponse="$(delegate ${jsonRequestFileName} 2>&1)"
#	result="$?"
#	if [ ${result} != "0" ] ; then
#		echo "[ERROR] : $(date) : Build failed for Project ID: ${thisProjectID}." >> ${STATUSFILE}
#		echo "Build failed for Project ID: ${thisProjectID}." >> ${LOGFILE}
#		echo """The response returned, if any, appears between the rows of equals signs below.
#===============================================================================
#${jsonResponse}
#===============================================================================
#""" >> ${LOGFILE}
#	else : 
#		echo "[INFO] : $(date) : Build completed for Project ID: ${thisProjectID}." >> ${STATUSFILE}
#		echo "Build completed for Project ID: ${thisProjectID}." >> ${LOGFILE}
#		#export TEST="True"
#	#	typical JSON file location:  /work/conjugate/gp/${thisProjectID}/logs/response.json 
#		echo """${jsonResponse}
#""" > "${jsonResponseFileName}"
#		# try doing it like the following so that all needed info is available.
#		. /sysetc/GlycoProtein_manage_build_output.bash 
#		# If necessary, do it this way with N different inputs (N, -ge 5, is not known at the moment)
#		## /sysetc/GlycoProtein_manage_build_output.bash "${OutputDir}" "${jsonResponseFileName}" "${GoodPdbDir}"
#	fi
#############
#  To here
#############
	echo "Build setup complete. About to process the build."
	process_the_build
	count="$((count+1))"
done < "${OutputDir}/provenance/Valid_Projects_List.txt"

